CREATE TABLE instituicoes (
    id BIGINT PRIMARY KEY AUTO_INCREMENT
  , nome VARCHAR(100) NOT NULL
  , cnpj VARCHAR(14) NOT NULL UNIQUE
  , tipo CHAR(1) NOT NULL
  , segmento VARCHAR(40) NOT NULL
  , created_at DATETIME
  , updated_at DATETIME
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
