CREATE TABLE instituicoes (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT
  , nome VARCHAR(100) NOT NULL
  , cnpj VARCHAR(14) NOT NULL UNIQUE
  , tipo CHAR(1) NOT NULL
  , segmento VARCHAR(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
